---
title: "Tables comparing observed network statistics at different time points with 95% intervals for bootstrap/jackknife differences and 95% intervals estimating the statistic using sampling by degree sequence"
author: "Alan Sun"
date: "7/20/2021"
output: 
  pdf_document:
      extra_dependencies: ["makecell"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(igraph)
load("env.RData")
```

# Friendship Network
```{r echo=FALSE}
tbd21 <- tboot_f2 - tboot_f1
tbd32 <- tboot_f3 - tboot_f2
tbd43 <- tboot_f4 - tboot_f3
tbd31 <- tboot_f3 - tboot_f1
tbd42 <- tboot_f4 - tboot_f2
tbd41 <- tboot_f4 - tboot_f1

tjd21 <- tjack_f2 - tjack_f1
tjd32 <- tjack_f3 - tjack_f2
tjd43 <- tjack_f4 - tjack_f3
tjd31 <- tjack_f3 - tjack_f1
tjd42 <- tjack_f4 - tjack_f2
tjd41 <- tjack_f4 - tjack_f1

CItbd21 <- round(quantile(tbd21, c(.025, .975)), 3)
CItjd21 <- round(quantile(tjd21, c(.025, .975)), 3)
CItbd32 <- round(quantile(tbd32, c(.025, .975)), 3)
CItjd32 <- round(quantile(tjd32, c(.025, .975)), 3)
CItbd43 <- round(quantile(tbd43, c(.025, .975)), 3)
CItjd43 <- round(quantile(tjd43, c(.025, .975)), 3)
CItbd31 <- round(quantile(tbd31, c(.025, .975)), 3)
CItjd31 <- round(quantile(tjd31, c(.025, .975)), 3)
CItbd42 <- round(quantile(tbd42, c(.025, .975)), 3)
CItjd42 <- round(quantile(tjd42, c(.025, .975)), 3)
CItbd41 <- round(quantile(tbd41, c(.025, .975)), 3)
CItjd41 <- round(quantile(tjd41, c(.025, .975)), 3)

mbd21 <- mboot_f2 - mboot_f1
mbd32 <- mboot_f3 - mboot_f2
mbd43 <- mboot_f4 - mboot_f3
mbd31 <- mboot_f3 - mboot_f1
mbd42 <- mboot_f4 - mboot_f2
mbd41 <- mboot_f4 - mboot_f1

mjd21 <- mjack_f2 - mjack_f1
mjd32 <- mjack_f3 - mjack_f2
mjd43 <- mjack_f4 - mjack_f3
mjd31 <- mjack_f3 - mjack_f1
mjd42 <- mjack_f4 - mjack_f2
mjd41 <- mjack_f4 - mjack_f1

CImbd21 <- round(quantile(mbd21, c(.025, .975)), 3)
CImjd21 <- round(quantile(mjd21, c(.025, .975)), 3)
CImbd32 <- round(quantile(mbd32, c(.025, .975)), 3)
CImjd32 <- round(quantile(mjd32, c(.025, .975)), 3)
CImbd43 <- round(quantile(mbd43, c(.025, .975)), 3)
CImjd43 <- round(quantile(mjd43, c(.025, .975)), 3)
CImbd31 <- round(quantile(mbd31, c(.025, .975)), 3)
CImjd31 <- round(quantile(mjd31, c(.025, .975)), 3)
CImbd42 <- round(quantile(mbd42, c(.025, .975)), 3)
CImjd42 <- round(quantile(mjd42, c(.025, .975)), 3)
CImbd41 <- round(quantile(mbd41, c(.025, .975)), 3)
CImjd41 <- round(quantile(mjd41, c(.025, .975)), 3)

dbd21 <- dboot_f2 - dboot_f1
dbd32 <- dboot_f3 - dboot_f2
dbd43 <- dboot_f4 - dboot_f3
dbd31 <- dboot_f3 - dboot_f1
dbd42 <- dboot_f4 - dboot_f2
dbd41 <- dboot_f4 - dboot_f1

djd21 <- djack_f2 - djack_f1
djd32 <- djack_f3 - djack_f2
djd43 <- djack_f4 - djack_f3
djd31 <- djack_f3 - djack_f1
djd42 <- djack_f4 - djack_f2
djd41 <- djack_f4 - djack_f1

CIdbd21 <- round(quantile(dbd21, c(.025, .975)), 3)
CIdjd21 <- round(quantile(djd21, c(.025, .975)), 3)
CIdbd32 <- round(quantile(dbd32, c(.025, .975)), 3)
CIdjd32 <- round(quantile(djd32, c(.025, .975)), 3)
CIdbd43 <- round(quantile(dbd43, c(.025, .975)), 3)
CIdjd43 <- round(quantile(djd43, c(.025, .975)), 3)
CIdbd31 <- round(quantile(dbd31, c(.025, .975)), 3)
CIdjd31 <- round(quantile(djd31, c(.025, .975)), 3)
CIdbd42 <- round(quantile(dbd42, c(.025, .975)), 3)
CIdjd42 <- round(quantile(djd42, c(.025, .975)), 3)
CIdbd41 <- round(quantile(dbd41, c(.025, .975)), 3)
CIdjd41 <- round(quantile(djd41, c(.025, .975)), 3)

kbd21 <- kboot_f2 - kboot_f1
kbd32 <- kboot_f3 - kboot_f2
kbd43 <- kboot_f4 - kboot_f3
kbd31 <- kboot_f3 - kboot_f1
kbd42 <- kboot_f4 - kboot_f2
kbd41 <- kboot_f4 - kboot_f1

kjd21 <- kjack_f2 - kjack_f1
kjd32 <- kjack_f3 - kjack_f2
kjd43 <- kjack_f4 - kjack_f3
kjd31 <- kjack_f3 - kjack_f1
kjd42 <- kjack_f4 - kjack_f2
kjd41 <- kjack_f4 - kjack_f1

CIkbd21 <- round(quantile(kbd21, c(.025, .975)), 3)
CIkjd21 <- round(quantile(kjd21, c(.025, .975)), 3)
CIkbd32 <- round(quantile(kbd32, c(.025, .975)), 3)
CIkjd32 <- round(quantile(kjd32, c(.025, .975)), 3)
CIkbd43 <- round(quantile(kbd43, c(.025, .975)), 3)
CIkjd43 <- round(quantile(kjd43, c(.025, .975)), 3)
CIkbd31 <- round(quantile(kbd31, c(.025, .975)), 3)
CIkjd31 <- round(quantile(kjd31, c(.025, .975)), 3)
CIkbd42 <- round(quantile(kbd42, c(.025, .975)), 3)
CIkjd42 <- round(quantile(kjd42, c(.025, .975)), 3)
CIkbd41 <- round(quantile(kbd41, c(.025, .975)), 3)
CIkjd41 <- round(quantile(kjd41, c(.025, .975)), 3)

tf1 <- transitivity(fg1)
tf2 <- transitivity(fg2)
tf3 <- transitivity(fg3)
tf4 <- transitivity(fg4)

mf1 <- mean(degree(fg1))
mf2 <- mean(degree(fg2))
mf3 <- mean(degree(fg3))
mf4 <- mean(degree(fg4))

df1 <- edge_density(fg1)
df2 <- edge_density(fg2)
df3 <- edge_density(fg3)
df4 <- edge_density(fg4)

kf1 <- sum(coreness(fg1) > 1)
kf2 <- sum(coreness(fg2) > 1)
kf3 <- sum(coreness(fg3) > 1)
kf4 <- sum(coreness(fg4) > 1)

ptb21 <- paste("boot:", "[", paste(CItbd21[1], CItbd21[2], sep=", "), "]")
ptj21 <- paste("jack:", "[", paste(CItjd21[1], CItjd21[2], sep=", "), "]")
pmb21 <- paste("boot:", "[", paste(CImbd21[1], CImbd21[2], sep=", "), "]")
pmj21 <- paste("jack:", "[", paste(CImjd21[1], CImjd21[2], sep=", "), "]")
pdb21 <- paste("boot:", "[", paste(CIdbd21[1], CIdbd21[2], sep=", "), "]")
pdj21 <- paste("jack:", "[", paste(CIdjd21[1], CIdjd21[2], sep=", "), "]")
pkb21 <- paste("boot:", "[", paste(CIkbd21[1], CIkbd21[2], sep=", "), "]")
pkj21 <- paste("jack:", "[", paste(CIkjd21[1], CIkjd21[2], sep=", "), "]")

ptb32 <- paste("boot:", "[", paste(CItbd32[1], CItbd32[2], sep=", "), "]")
ptj32 <- paste("jack:", "[", paste(CItjd32[1], CItjd32[2], sep=", "), "]")
pmb32 <- paste("boot:", "[", paste(CImbd32[1], CImbd32[2], sep=", "), "]")
pmj32 <- paste("jack:", "[", paste(CImjd32[1], CImjd32[2], sep=", "), "]")
pdb32 <- paste("boot:", "[", paste(CIdbd32[1], CIdbd32[2], sep=", "), "]")
pdj32 <- paste("jack:", "[", paste(CIdjd32[1], CIdjd32[2], sep=", "), "]")
pkb32 <- paste("boot:", "[", paste(CIkbd32[1], CIkbd32[2], sep=", "), "]")
pkj32 <- paste("jack:", "[", paste(CIkjd32[1], CIkjd32[2], sep=", "), "]")

ptb43 <- paste("boot:", "[", paste(CItbd43[1], CItbd43[2], sep=", "), "]")
ptj43 <- paste("jack:", "[", paste(CItjd43[1], CItjd43[2], sep=", "), "]")
pmb43 <- paste("boot:", "[", paste(CImbd43[1], CImbd43[2], sep=", "), "]")
pmj43 <- paste("jack:", "[", paste(CImjd43[1], CImjd43[2], sep=", "), "]")
pdb43 <- paste("boot:", "[", paste(CIdbd43[1], CIdbd43[2], sep=", "), "]")
pdj43 <- paste("jack:", "[", paste(CIdjd43[1], CIdjd43[2], sep=", "), "]")
pkb43 <- paste("boot:", "[", paste(CIkbd43[1], CIkbd43[2], sep=", "), "]")
pkj43 <- paste("jack:", "[", paste(CIkjd43[1], CIkjd43[2], sep=", "), "]")

ptb31 <- paste("boot:", "[", paste(CItbd31[1], CItbd31[2], sep=", "), "]")
ptj31 <- paste("jack:", "[", paste(CItjd31[1], CItjd31[2], sep=", "), "]")
pmb31 <- paste("boot:", "[", paste(CImbd31[1], CImbd31[2], sep=", "), "]")
pmj31 <- paste("jack:", "[", paste(CImjd31[1], CImjd31[2], sep=", "), "]")
pdb31 <- paste("boot:", "[", paste(CIdbd31[1], CIdbd31[2], sep=", "), "]")
pdj31 <- paste("jack:", "[", paste(CIdjd31[1], CIdjd31[2], sep=", "), "]")
pkb31 <- paste("boot:", "[", paste(CIkbd31[1], CIkbd31[2], sep=", "), "]")
pkj31 <- paste("jack:", "[", paste(CIkjd31[1], CIkjd31[2], sep=", "), "]")

ptb42 <- paste("boot:", "[", paste(CItbd42[1], CItbd42[2], sep=", "), "]")
ptj42 <- paste("jack:", "[", paste(CItjd42[1], CItjd42[2], sep=", "), "]")
pmb42 <- paste("boot:", "[", paste(CImbd42[1], CImbd42[2], sep=", "), "]")
pmj42 <- paste("jack:", "[", paste(CImjd42[1], CImjd42[2], sep=", "), "]")
pdb42 <- paste("boot:", "[", paste(CIdbd42[1], CIdbd42[2], sep=", "), "]")
pdj42 <- paste("jack:", "[", paste(CIdjd42[1], CIdjd42[2], sep=", "), "]")
pkb42 <- paste("boot:", "[", paste(CIkbd42[1], CIkbd42[2], sep=", "), "]")
pkj42 <- paste("jack:", "[", paste(CIkjd42[1], CIkjd42[2], sep=", "), "]")

ptb41 <- paste("boot:", "[", paste(CItbd41[1], CItbd41[2], sep=", "), "]")
ptj41 <- paste("jack:", "[", paste(CItjd41[1], CItjd41[2], sep=", "), "]")
pmb41 <- paste("boot:", "[", paste(CImbd41[1], CImbd41[2], sep=", "), "]")
pmj41 <- paste("jack:", "[", paste(CImjd41[1], CImjd41[2], sep=", "), "]")
pdb41 <- paste("boot:", "[", paste(CIdbd41[1], CIdbd41[2], sep=", "), "]")
pdj41 <- paste("jack:", "[", paste(CIdjd41[1], CIdjd41[2], sep=", "), "]")
pkb41 <- paste("boot:", "[", paste(CIkbd41[1], CIkbd41[2], sep=", "), "]")
pkj41 <- paste("jack:", "[", paste(CIkjd41[1], CIkjd41[2], sep=", "), "]")

tCIdseq1 <- round(quantile(tdeg_f1, c(.025, .975)), 3)
tCIdseq2 <- round(quantile(tdeg_f2, c(.025, .975)), 3)
tCIdseq3 <- round(quantile(tdeg_f3, c(.025, .975)), 3)
tCIdseq4 <- round(quantile(tdeg_f4, c(.025, .975)), 3)

mCIdseq1 <- round(quantile(mdeg_f1, c(.025, .975)), 3)
mCIdseq2 <- round(quantile(mdeg_f2, c(.025, .975)), 3)
mCIdseq3 <- round(quantile(mdeg_f3, c(.025, .975)), 3)
mCIdseq4 <- round(quantile(mdeg_f4, c(.025, .975)), 3)

dCIdseq1 <- round(quantile(ddeg_f1, c(.025, .975)), 3)
dCIdseq2 <- round(quantile(ddeg_f2, c(.025, .975)), 3)
dCIdseq3 <- round(quantile(ddeg_f3, c(.025, .975)), 3)
dCIdseq4 <- round(quantile(ddeg_f4, c(.025, .975)), 3)

kCIdseq1 <- round(quantile(kdeg_f1, c(.025, .975)), 3)
kCIdseq2 <- round(quantile(kdeg_f2, c(.025, .975)), 3)
kCIdseq3 <- round(quantile(kdeg_f3, c(.025, .975)), 3)
kCIdseq4 <- round(quantile(kdeg_f4, c(.025, .975)), 3)

ptd1 <- paste("DSE:", "[", paste(tCIdseq1[1], tCIdseq1[2], sep=", "), "]")
ptd2 <- paste("DSE:", "[", paste(tCIdseq2[1], tCIdseq2[2], sep=", "), "]")
ptd3 <- paste("DSE:", "[", paste(tCIdseq3[1], tCIdseq3[2], sep=", "), "]")
ptd4 <- paste("DSE:", "[", paste(tCIdseq4[1], tCIdseq4[2], sep=", "), "]")

pkd1 <- paste("DSE:", "[", paste(kCIdseq1[1], kCIdseq1[2], sep=", "), "]")
pkd2 <- paste("DSE:", "[", paste(kCIdseq2[1], kCIdseq2[2], sep=", "), "]")
pkd3 <- paste("DSE:", "[", paste(kCIdseq3[1], kCIdseq3[2], sep=", "), "]")
pkd4 <- paste("DSE:", "[", paste(kCIdseq4[1], kCIdseq4[2], sep=", "), "]")
```

```{=latex}
\begin{center}
Time points 1 and 2
\end{center}

\begin{center}
\begin{table}[h]
\begin{tabular}{|l|l|l|l|l|l|}
\hline
\textbf{Statistic} & \textbf{T1} & \textbf{T2} & \textbf{T2 - T1} & \textbf{95\% difference interval} \\
\hline
Transitivity & \makecell[l]{`r round(tf1, 3)` \\ `r ptd1`} & \makecell[l]{`r round(tf2, 3)` \\ `r ptd2`} & `r round(tf2-tf1, 3)` & \makecell[l]{`r ptb21` \\ `r ptj21`} \\
\hline
Mean Degree & `r round(mf1, 3)` & `r round(mf2, 3)` & `r round(mf2-mf1, 3)` & \makecell[l]{`r pmb21` \\ `r pmj21`} \\
\hline
Edge Density & `r round(df1, 3)` & `r round(df2, 3)` & `r round(df2-df1, 3)` & \makecell[l]{`r pdb21` \\ `r pdj21`} \\
\hline
Coreness, k > 1 & \makecell[l]{`r round(kf1, 3)` \\ `r pkd1`} & \makecell[l]{`r round(kf2, 3)` \\ `r pkd2`} & `r round(kf2-kf1, 3)` & \makecell[l]{`r pkb21` \\ `r pkj21`} \\
\hline
\end{tabular}
\caption{Note: \emph{DSE} indicates the 95\% C.I. of the statistic as estimated by resampling the network 1000 times using its degree sequence.}
\end{table}
\end{center}

\begin{center}
Time points 2 and 3
\end{center}

\begin{center}
\begin{tabular}{|l|l|l|l|l|l|}
\hline
\textbf{Statistic} & \textbf{T2} & \textbf{T3} & \textbf{T3 - T2} & \textbf{95\% difference interval} \\
\hline
Transitivity & \makecell[l]{`r round(tf2, 3)` \\ `r ptd2`} & \makecell[l]{`r round(tf3, 3)` \\ `r ptd3`} & `r round(tf3-tf2, 3)` & \makecell[l]{`r ptb32` \\ `r ptj32`} \\
\hline
Mean Degree & `r round(mf2, 3)` & `r round(mf3, 3)` & `r round(mf3-mf2, 3)` & \makecell[l]{`r pmb32` \\ `r pmj32`} \\
\hline
Edge Density & `r round(df2, 3)` & `r round(df3, 3)` & `r round(df3-df2, 3)` & \makecell[l]{`r pdb32` \\ `r pdj32`} \\
\hline
Coreness, k > 1 & \makecell[l]{`r round(kf2, 3)` \\ `r pkd2`} & \makecell[l]{`r round(kf3, 3)` \\ `r pkd3`} & `r round(kf3-kf2, 3)` & \makecell[l]{`r pkb32` \\ `r pkj32`} \\
\hline
\end{tabular}
\end{center}

\newpage

\begin{center}
Time points 3 and 4
\end{center}

\begin{center}
\begin{tabular}{|l|l|l|l|l|l|}
\hline
\textbf{Statistic} & \textbf{T3} & \textbf{T4} & \textbf{T4 - T3} & \textbf{95\% difference interval} \\
\hline
Transitivity & \makecell[l]{`r round(tf3, 3)` \\ `r ptd3`} & \makecell[l]{`r round(tf4, 3)` \\ `r ptd4`} & `r round(tf4-tf3, 3)` & \makecell[l]{`r ptb43` \\ `r ptj43`} \\
\hline
Mean Degree & `r round(mf3, 3)` & `r round(mf4, 3)` & `r round(mf4-mf3, 3)` & \makecell[l]{`r pmb43` \\ `r pmj43`} \\
\hline
Edge Density & `r round(df3, 3)` & `r round(df4, 3)` & `r round(df4-df3, 3)` & \makecell[l]{`r pdb43` \\ `r pdj43`} \\
\hline
Coreness, k > 1 & \makecell[l]{`r round(kf3, 3)` \\ `r pkd3`} & \makecell[l]{`r round(kf4, 3)` \\ `r pkd4`} & `r round(kf4-kf3, 3)` & \makecell[l]{`r pkb43` \\ `r pkj43`} \\
\hline
\end{tabular}
\end{center}

\bigskip

\bigskip

\begin{center}
Time points 1 and 3
\end{center}

\begin{center}
\begin{tabular}{|l|l|l|l|l|l|}
\hline
\textbf{Statistic} & \textbf{T1} & \textbf{T3} & \textbf{T3 - T1} & \textbf{95\% difference interval} \\
\hline
Transitivity & \makecell[l]{`r round(tf1, 3)` \\ `r ptd1`} & \makecell[l]{`r round(tf3, 3)` \\ `r ptd3`} & `r round(tf3-tf1, 3)` & \makecell[l]{`r ptb31` \\ `r ptj31`} \\
\hline
Mean Degree & `r round(mf1, 3)` & `r round(mf3, 3)` & `r round(mf3-mf1, 3)` & \makecell[l]{`r pmb31` \\ `r pmj31`} \\
\hline
Edge Density & `r round(df1, 3)` & `r round(df3, 3)` & `r round(df3-df1, 3)` & \makecell[l]{`r pdb31` \\ `r pdj31`} \\
\hline
Coreness, k > 1 & \makecell[l]{`r round(kf1, 3)` \\ `r pkd1`} & \makecell[l]{`r round(kf3, 3)` \\ `r pkd3`} & `r round(kf3-kf1, 3)` & \makecell[l]{`r pkb31` \\ `r pkj31`} \\
\hline
\end{tabular}
\end{center}

\bigskip

\bigskip

\begin{center}
Time points 2 and 4
\end{center}

\begin{center}
\begin{tabular}{|l|l|l|l|l|l|}
\hline
\textbf{Statistic} & \textbf{T2} & \textbf{T4} & \textbf{T4 - T2} & \textbf{95\% difference interval} \\
\hline
Transitivity & \makecell[l]{`r round(tf2, 3)` \\ `r ptd2`} & \makecell[l]{`r round(tf4, 3)` \\ `r ptd4`} & `r round(tf4-tf2, 3)` & \makecell[l]{`r ptb42` \\ `r ptj42`} \\
\hline
Mean Degree & `r round(mf2, 3)` & `r round(mf4, 3)` & `r round(mf4-mf2, 3)` & \makecell[l]{`r pmb42` \\ `r pmj42`} \\
\hline
Edge Density & `r round(df2, 3)` & `r round(df4, 3)` & `r round(df4-df2, 3)` & \makecell[l]{`r pdb42` \\ `r pdj42`} \\
\hline
Coreness, k > 1 & \makecell[l]{`r round(kf2, 3)` \\ `r pkd2`} & \makecell[l]{`r round(kf4, 3)` \\ `r pkd4`} & `r round(kf4-kf2, 3)` & \makecell[l]{`r pkb42` \\ `r pkj42`} \\
\hline
\end{tabular}
\end{center}

\bigskip

\bigskip

\begin{center}
Time points 1 and 4
\end{center}

\begin{center}
\begin{tabular}{|l|l|l|l|l|l|}
\hline
\textbf{Statistic} & \textbf{T1} & \textbf{T4} & \textbf{T4 - T1} & \textbf{95\% difference interval} \\
\hline
Transitivity & \makecell[l]{`r round(tf1, 3)` \\ `r ptd1`} & \makecell[l]{`r round(tf4, 3)` \\ `r ptd4`} & `r round(tf4-tf1, 3)` & \makecell[l]{`r ptb41` \\ `r ptj41`} \\
\hline
Mean Degree & `r round(mf1, 3)` & `r round(mf4, 3)` & `r round(mf4-mf1, 3)` & \makecell[l]{`r pmb41` \\ `r pmj41`} \\
\hline
Edge Density & `r round(df1, 3)` & `r round(df4, 3)` & `r round(df4-df1, 3)` & \makecell[l]{`r pdb41` \\ `r pdj41`} \\
\hline
Coreness, k > 1 & \makecell[l]{`r round(kf1, 3)` \\ `r pkd1`} & \makecell[l]{`r round(kf4, 3)` \\ `r pkd4`} & `r round(kf4-kf1, 3)` & \makecell[l]{`r pkb41` \\ `r pkj41`} \\
\hline
\end{tabular}
\end{center}

\newpage
```

# Tortoise Network
```{r echo=FALSE}
tbd9897 <- tboot_t98 - tboot_t97
tbd9998 <- tboot_t99 - tboot_t98
tbd9997 <- tboot_t99 - tboot_t97

tjd9897 <- tjack_t98 - tjack_t97
tjd9998 <- tjack_t99 - tjack_t98
tjd9997 <- tjack_t99 - tjack_t97

CItbd9897 <- round(quantile(tbd9897, c(.025, .975)), 3)
CItjd9897 <- round(quantile(tjd9897, c(.025, .975)), 3)
CItbd9998 <- round(quantile(tbd9998, c(.025, .975)), 3)
CItjd9998 <- round(quantile(tjd9998, c(.025, .975)), 3)
CItbd9997 <- round(quantile(tbd9997, c(.025, .975)), 3)
CItjd9997 <- round(quantile(tjd9997, c(.025, .975)), 3)

mbd9897 <- mboot_t98 - mboot_t97
mbd9998 <- mboot_t99 - mboot_t98
mbd9997 <- mboot_t99 - mboot_t97

mjd9897 <- mjack_t98 - mjack_t97
mjd9998 <- mjack_t99 - mjack_t98
mjd9997 <- mjack_t99 - mjack_t97

CImbd9897 <- round(quantile(mbd9897, c(.025, .975)), 3)
CImjd9897 <- round(quantile(mjd9897, c(.025, .975)), 3)
CImbd9998 <- round(quantile(mbd9998, c(.025, .975)), 3)
CImjd9998 <- round(quantile(mjd9998, c(.025, .975)), 3)
CImbd9997 <- round(quantile(mbd9997, c(.025, .975)), 3)
CImjd9997 <- round(quantile(mjd9997, c(.025, .975)), 3)

dbd9897 <- dboot_t98 - dboot_t97
dbd9998 <- dboot_t99 - dboot_t98
dbd9997 <- dboot_t99 - dboot_t97

djd9897 <- djack_t98 - djack_t97
djd9998 <- djack_t99 - djack_t98
djd9997 <- djack_t99 - djack_t97

CIdbd9897 <- round(quantile(dbd9897, c(.025, .975)), 3)
CIdjd9897 <- round(quantile(djd9897, c(.025, .975)), 3)
CIdbd9998 <- round(quantile(dbd9998, c(.025, .975)), 3)
CIdjd9998 <- round(quantile(djd9998, c(.025, .975)), 3)
CIdbd9997 <- round(quantile(dbd9997, c(.025, .975)), 3)
CIdjd9997 <- round(quantile(djd9997, c(.025, .975)), 3)

kbd9897 <- kboot_t98 - kboot_t97
kbd9998 <- kboot_t99 - kboot_t98
kbd9997 <- kboot_t99 - kboot_t97

kjd9897 <- kjack_t98 - kjack_t97
kjd9998 <- kjack_t99 - kjack_t98
kjd9997 <- kjack_t99 - kjack_t97

CIkbd9897 <- round(quantile(kbd9897, c(.025, .975)), 3)
CIkjd9897 <- round(quantile(kjd9897, c(.025, .975)), 3)
CIkbd9998 <- round(quantile(kbd9998, c(.025, .975)), 3)
CIkjd9998 <- round(quantile(kjd9998, c(.025, .975)), 3)
CIkbd9997 <- round(quantile(kbd9997, c(.025, .975)), 3)
CIkjd9997 <- round(quantile(kjd9997, c(.025, .975)), 3)

tt97 <- transitivity(tg97)
tt98 <- transitivity(tg98)
tt99 <- transitivity(tg99)

mt97 <- mean(degree(tg97))
mt98 <- mean(degree(tg98))
mt99 <- mean(degree(tg99))

dt97 <- edge_density(tg97)
dt98 <- edge_density(tg98)
dt99 <- edge_density(tg99)

kt97 <- sum(coreness(tg97) > 1)
kt98 <- sum(coreness(tg98) > 1)
kt99 <- sum(coreness(tg99) > 1)

ptb9897 <- paste("boot:", "[", paste(CItbd9897[1], CItbd9897[2], sep=", "), "]")
ptj9897 <- paste("jack:", "[", paste(CItjd9897[1], CItjd9897[2], sep=", "), "]")
pmb9897 <- paste("boot:", "[", paste(CImbd9897[1], CImbd9897[2], sep=", "), "]")
pmj9897 <- paste("jack:", "[", paste(CImjd9897[1], CImjd9897[2], sep=", "), "]")
pdb9897 <- paste("boot:", "[", paste(CIdbd9897[1], CIdbd9897[2], sep=", "), "]")
pdj9897 <- paste("jack:", "[", paste(CIdjd9897[1], CIdjd9897[2], sep=", "), "]")
pkb9897 <- paste("boot:", "[", paste(CIkbd9897[1], CIkbd9897[2], sep=", "), "]")
pkj9897 <- paste("jack:", "[", paste(CIkjd9897[1], CIkjd9897[2], sep=", "), "]")

ptb9998 <- paste("boot:", "[", paste(CItbd9998[1], CItbd9998[2], sep=", "), "]")
ptj9998 <- paste("jack:", "[", paste(CItjd9998[1], CItjd9998[2], sep=", "), "]")
pmb9998 <- paste("boot:", "[", paste(CImbd9998[1], CImbd9998[2], sep=", "), "]")
pmj9998 <- paste("jack:", "[", paste(CImjd9998[1], CImjd9998[2], sep=", "), "]")
pdb9998 <- paste("boot:", "[", paste(CIdbd9998[1], CIdbd9998[2], sep=", "), "]")
pdj9998 <- paste("jack:", "[", paste(CIdjd9998[1], CIdjd9998[2], sep=", "), "]")
pkb9998 <- paste("boot:", "[", paste(CIkbd9998[1], CIkbd9998[2], sep=", "), "]")
pkj9998 <- paste("jack:", "[", paste(CIkjd9998[1], CIkjd9998[2], sep=", "), "]")

ptb9997 <- paste("boot:", "[", paste(CItbd9997[1], CItbd9997[2], sep=", "), "]")
ptj9997 <- paste("jack:", "[", paste(CItjd9997[1], CItjd9997[2], sep=", "), "]")
pmb9997 <- paste("boot:", "[", paste(CImbd9997[1], CImbd9997[2], sep=", "), "]")
pmj9997 <- paste("jack:", "[", paste(CImjd9997[1], CImjd9997[2], sep=", "), "]")
pdb9997 <- paste("boot:", "[", paste(CIdbd9997[1], CIdbd9997[2], sep=", "), "]")
pdj9997 <- paste("jack:", "[", paste(CIdjd9997[1], CIdjd9997[2], sep=", "), "]")
pkb9997 <- paste("boot:", "[", paste(CIkbd9997[1], CIkbd9997[2], sep=", "), "]")
pkj9997 <- paste("jack:", "[", paste(CIkjd9997[1], CIkjd9997[2], sep=", "), "]")

tCIdseq1 <- round(quantile(tdeg_tg97, c(.025, .975)), 3)
tCIdseq2 <- round(quantile(tdeg_tg98, c(.025, .975)), 3)
tCIdseq3 <- round(quantile(tdeg_tg99, c(.025, .975)), 3)

mCIdseq1 <- round(quantile(mdeg_tg97, c(.025, .975)), 3)
mCIdseq2 <- round(quantile(mdeg_tg98, c(.025, .975)), 3)
mCIdseq3 <- round(quantile(mdeg_tg99, c(.025, .975)), 3)

dCIdseq1 <- round(quantile(ddeg_tg97, c(.025, .975)), 3)
dCIdseq2 <- round(quantile(ddeg_tg98, c(.025, .975)), 3)
dCIdseq3 <- round(quantile(ddeg_tg99, c(.025, .975)), 3)

kCIdseq1 <- round(quantile(kdeg_tg97, c(.025, .975)), 3)
kCIdseq2 <- round(quantile(kdeg_tg98, c(.025, .975)), 3)
kCIdseq3 <- round(quantile(kdeg_tg99, c(.025, .975)), 3)

ptd1 <- paste("DSE:", "[", paste(tCIdseq1[1], tCIdseq1[2], sep=", "), "]")
ptd2 <- paste("DSE:", "[", paste(tCIdseq2[1], tCIdseq2[2], sep=", "), "]")
ptd3 <- paste("DSE:", "[", paste(tCIdseq3[1], tCIdseq3[2], sep=", "), "]")

pkd1 <- paste("DSE:", "[", paste(kCIdseq1[1], kCIdseq1[2], sep=", "), "]")
pkd2 <- paste("DSE:", "[", paste(kCIdseq2[1], kCIdseq2[2], sep=", "), "]")
pkd3 <- paste("DSE:", "[", paste(kCIdseq3[1], kCIdseq3[2], sep=", "), "]")
```

```{=latex}
\begin{center}
1997 and 1998
\end{center}

\begin{center}
\begin{table}[h]
\begin{tabular}{|l|l|l|l|l|l|}
\hline
\textbf{Statistic} & \textbf{1997} & \textbf{1998} & \textbf{1998 - 1997} & \textbf{95\% difference interval} \\
\hline
Transitivity & \makecell[l]{`r round(tt97, 3)` \\ `r ptd1`} & \makecell[l]{`r round(tt98, 3)` \\ `r ptd2`} & `r round(tt98-tt97, 3)` & \makecell[l]{`r ptb9897` \\ `r ptj9897`} \\
\hline
Mean Degree & `r round(mt97, 3)` & `r round(mt98, 3)` & `r round(mt98-mt97, 3)` & \makecell[l]{`r pmb9897` \\ `r pmj9897`} \\
\hline
Edge Density & `r round(dt97, 3)` & `r round(dt98, 3)` & `r round(dt98-dt97, 3)` & \makecell[l]{`r pdb9897` \\ `r pdj9897`} \\
\hline
Coreness, k > 1 & \makecell[l]{`r round(kt97, 3)` \\ `r pkd1`} & \makecell[l]{`r round(kt98, 3)` \\ `r pkd2`} & `r round(kt98-kt97, 3)` & \makecell[l]{`r pkb9897` \\ `r pkj9897`} \\
\hline
\end{tabular}
\end{table}
\end{center}

\begin{center}
1998 and 1999
\end{center}

\begin{center}
\begin{tabular}{|l|l|l|l|l|l|}
\hline
\textbf{Statistic} & \textbf{1998} & \textbf{1999} & \textbf{1999 - 1998} & \textbf{95\% difference interval} \\
\hline
Transitivity & \makecell[l]{`r round(tt98, 3)` \\ `r ptd2`} & \makecell[l]{`r round(tt99, 3)` \\ `r ptd3`} & `r round(tt99-tt98, 3)` & \makecell[l]{`r ptb9998` \\ `r ptj9998`} \\
\hline
Mean Degree & `r round(mt98, 3)` & `r round(mt99, 3)` & `r round(mt99-mt98, 3)` & \makecell[l]{`r pmb9998` \\ `r pmj9998`} \\
\hline
Edge Density & `r round(dt98, 3)` & `r round(dt99, 3)` & `r round(dt99-dt98, 3)` & \makecell[l]{`r pdb9998` \\ `r pdj9998`} \\
\hline
Coreness, k > 1 & \makecell[l]{`r round(kt98, 3)` \\ `r pkd2`} & \makecell[l]{`r round(kt99, 3)` \\ `r pkd3`} & `r round(kt99-kt98, 3)` & \makecell[l]{`r pkb9998` \\ `r pkj9998`} \\
\hline
\end{tabular}
\end{center}

\bigskip

\bigskip

\begin{center}
1997 and 1999
\end{center}

\begin{center}
\begin{tabular}{|l|l|l|l|l|l|}
\hline
\textbf{Statistic} & \textbf{1997} & \textbf{1999} & \textbf{1999 - 1997} & \textbf{95\% difference interval} \\
\hline
Transitivity & \makecell[l]{`r round(tt97, 3)` \\ `r ptd1`} & \makecell[l]{`r round(tt99, 3)` \\ `r ptd3`} & `r round(tt99-tt97, 3)` & \makecell[l]{`r ptb9997` \\ `r ptj9997`} \\
\hline
Mean Degree & `r round(mt97, 3)` & `r round(mt99, 3)` & `r round(mt99-mt97, 3)` & \makecell[l]{`r pmb9997` \\ `r pmj9997`} \\
\hline
Edge Density & `r round(dt97, 3)` & `r round(dt99, 3)` & `r round(dt99-dt97, 3)` & \makecell[l]{`r pdb9997` \\ `r pdj9997`} \\
\hline
Coreness, k > 1 & \makecell[l]{`r round(kt97, 3)` \\ `r pkd1`} & \makecell[l]{`r round(kt99, 3)` \\ `r pkd3`} & `r round(kt99-kt97, 3)` & \makecell[l]{`r pkb9997` \\ `r pkj9997`} \\
\hline
\end{tabular}
\end{center}
```